### ISSUE TITLE
[Forge] Overlay and results in overworld brings me to 0fps

### ISSUE THREAD

**Issue by aaronhowser1** [tasgon/observable#8]
![image](https://user-images.githubusercontent.com/15698722/128138639-b3738a08-997c-4218-8321-df22f6677306.png)
The above is with 32 render distance, below is 16:
![image](https://user-images.githubusercontent.com/15698722/128139967-82c63de2-2606-41f0-85a8-548e8bacbb1c.png)

16 with overlay disabled:
![image](https://user-images.githubusercontent.com/15698722/128140151-9baeb963-ef52-4923-88d1-ecbcb0e25ed7.png)

![image](https://user-images.githubusercontent.com/15698722/128140333-ce92bef6-dc76-4186-854d-11974df8a12c.png)
Here's after opening the results. It might be lagging because there's so many things? Idk.

It crashed within a couple seconds, here's that crash report: https://pastebin.com/cpyDGL1i

**Comment by aaronhowser1** [comment]
The results would also lead you to believe that it's lagging massively, but it's at 20 tps.

**Comment by tasgon** [comment]
The crash (I suspect) is happening for the same reason as #5, which will be fixed momentarily. As for the performance, I suspect that's being caused by the text renderer having to query a couple hundred thousand items to see if they're in range, so my two options are either some kind of spatial hashing or just refusing to render text in the world. (Either that or somehow cache text VBOs, but I haven't been able to find any resources on that.) Which option sounds best for you?

**Comment by aaronhowser1** [comment]
Can it limit it to like the 1000 nearest ones or something? And only refresh every 10 seconds. Both should be configurable for best UX.

If it were just rendering text in the world (I assume you mean the text on the block) why would it be lagging in the last picture that has Overlay disabled but has the Results menu open?

**Comment by tasgon** [comment]
> Can it limit it to like the 1000 nearest ones or something?

Text (for block timings) is limited to a 128 block radius when it comes to rendering. The issue comes in when the game has to loop through all elements to find the ones that satisfy that condition.

> why would it be lagging in the last picture that has Overlay disabled but has the Results menu open?

That's because the results menu is also looping over every element. I'm going to add pagination after I fix the crashing issue, give me about a half hour total.

**Comment by tasgon** [comment]
The text issue is fixed in master

**Comment by tasgon** [comment]
Is this issue still happening for you, or can I close this?

**Comment by aaronhowser1** [comment]
I haven't tested it, I'll try the newest update now

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/129973598-ff62c372-6f99-4854-a8f2-2644f23abaa8.png)
Big improvement on fps!

It crashed immediately after taking that screenshot: https://pastebin.com/eyp6M1dG

**Comment by tasgon** [comment]
Crash should be fixed in the latest version

**Comment by aaronhowser1** [comment]
Awesome, no crashes from ten minutes of mucking around with it. FPS issues are also entirely gone.
